-- Minimal shared item registry for the first Roblox inventory slice.
-- Keep this Roblox-native, but close to QBCore's item shape so later qb-* ports can
-- ask for labels, weight, unique/useable flags, and descriptions in familiar ways.

return {
	sandwich = {
		name = "sandwich",
		label = "Sandwich",
		weight = 200,
		type = "item",
		image = "rbxassetid://71205215813861",
		unique = false,
		useable = true,
		shouldClose = true,
		removeOnUse = true,
		consume = { hunger = 25 },
		description = "Simple food for getting hunger back up.",
	},

	water_bottle = {
		name = "water_bottle",
		label = "Water Bottle",
		weight = 500,
		type = "item",
		image = "rbxassetid://102310364648557",
		unique = false,
		useable = true,
		shouldClose = true,
		removeOnUse = true,
		consume = { thirst = 30 },
		description = "Clean water for getting thirst back up.",
	},

	coffee = {
		name = "coffee",
		label = "Coffee",
		weight = 200,
		type = "item",
		image = "",
		unique = false,
		useable = true,
		shouldClose = true,
		removeOnUse = true,
		consume = { thirst = 12 },
		description = "A quick drink that helps a little.",
	},

	bandage = {
		name = "bandage",
		label = "Bandage",
		weight = 100,
		type = "item",
		image = "rbxassetid://127507281128765",
		unique = false,
		useable = true,
		shouldClose = true,
		removeOnUse = true,
		medical = { action = "heal", health = 20 },
		description = "Basic field dressing that restores a little health.",
	},

	firstaid = {
		name = "firstaid",
		label = "First Aid Kit",
		weight = 750,
		type = "item",
		image = "rbxassetid://114475477455604",
		unique = false,
		useable = true,
		shouldClose = true,
		removeOnUse = true,
		medical = { action = "revive", reviveHealth = 40, reviveDistance = 10, job = "ambulance" },
		description = "EMS kit used to revive a dead character nearby.",
	},

	armor = {
		name = "armor",
		label = "Armor",
		weight = 3000,
		type = "item",
		image = "rbxassetid://102433058305589",
		unique = false,
		useable = true,
		shouldClose = true,
		removeOnUse = true,
		medical = { action = "armor", amount = 100 },
		description = "Protective vest that restores armor.",
	},

	lockpick = {
		name = "lockpick",
		label = "Lockpick",
		weight = 300,
		type = "item",
		image = "",
		unique = false,
		useable = false,
		shouldClose = true,
		description = "A small tool for future systems.",
	},

	bank_card = {
		name = "bank_card",
		label = "Bank Card",
		weight = 10,
		type = "item",
		image = "rbxassetid://132842608229461",
		unique = true,
		useable = false,
		shouldClose = true,
		description = "A personal bank card used to access ATMs.",
	},

	phone = {
		name = "phone",
		label = "Smartphone",
		weight = 190,
		type = "item",
		image = "rbxassetid://76605475742515",
		unique = true,
		useable = true,
		shouldClose = true,
		removeOnUse = false,
		description = "A StudOS smartphone. Use this item to open it.",
	},

	-- Ammo items: one item is one bullet. A weapon lists which item it reloads
	-- from via weapon.ammoItem; reload pulls from these and is refused without them.
	pistol_ammo = {
		name = "pistol_ammo",
		label = "Pistol Ammo",
		weight = 15,
		type = "item",
		image = "rbxassetid://140301770604821",
		unique = false,
		useable = false,
		shouldClose = true,
		description = "A single pistol round.",
	},

	smg_ammo = {
		name = "smg_ammo",
		label = "SMG Ammo",
		weight = 10,
		type = "item",
		image = "rbxassetid://103901562160805",
		unique = false,
		useable = false,
		shouldClose = true,
		description = "A single SMG round.",
	},

	shotgun_ammo = {
		name = "shotgun_ammo",
		label = "Shotgun Shell",
		weight = 45,
		type = "item",
		image = "rbxassetid://71087877536303",
		unique = false,
		useable = false,
		shouldClose = true,
		description = "A single shotgun shell.",
	},

	rifle_ammo = {
		name = "rifle_ammo",
		label = "Rifle Ammo",
		weight = 20,
		type = "item",
		image = "rbxassetid://106240482458110",
		unique = false,
		useable = false,
		shouldClose = true,
		description = "A single rifle round.",
	},

	sniper_ammo = {
		name = "sniper_ammo",
		label = "Sniper Ammo",
		weight = 30,
		type = "item",
		image = "rbxassetid://106240482458110",
		unique = false,
		useable = false,
		shouldClose = true,
		description = "A single high-caliber sniper round.",
	},

	bolt_ammo = {
		name = "bolt_ammo",
		label = "Crossbow Bolt",
		weight = 60,
		type = "item",
		image = "",
		unique = false,
		useable = false,
		shouldClose = true,
		description = "A single crossbow bolt.",
	},

	grenade_ammo = {
		name = "grenade_ammo",
		label = "Grenade Round",
		weight = 400,
		type = "item",
		image = "",
		unique = false,
		useable = false,
		shouldClose = true,
		description = "A single grenade launcher round.",
	},

	rocket_ammo = {
		name = "rocket_ammo",
		label = "Rocket",
		weight = 1500,
		type = "item",
		image = "",
		unique = false,
		useable = false,
		shouldClose = true,
		description = "A single rocket.",
	},

	railgun_ammo = {
		name = "railgun_ammo",
		label = "Railgun Slug",
		weight = 100,
		type = "item",
		image = "",
		unique = false,
		useable = false,
		shouldClose = true,
		description = "A single railgun slug.",
	},

	weapon_pistol = {
		name = "weapon_pistol",
		label = "Pistol",
		weight = 1000,
		type = "weapon",
		image = "rbxassetid://87027334862824",
		unique = true,
		useable = true,
		shouldClose = true,
		removeOnUse = false,
		weapon = {
			toolName = "Pistol",
			ammoItem = "pistol_ammo",
			config = {
				AmmoCapacity = 17,
				GravityFactor = 0.5,
				HitDamage = 20,
				MaxSpread = 2,
				MuzzleFlashSize0 = 0.7,
				MuzzleFlashSize1 = 0.9,
				RecoilDecay = 0.8,
				RecoilMax = 1.2,
				RecoilMin = 1.1,
				ShotCooldown = 0.2,
				TotalRecoilMax = 1.3,
			},
		},
		description = "A compact sidearm backed by a Roblox Tool template.",
	},

	weapon_shotgun = {
		name = "weapon_shotgun",
		label = "Shotgun",
		weight = 3500,
		type = "weapon",
		image = "rbxassetid://83204137206876",
		unique = true,
		useable = true,
		shouldClose = true,
		removeOnUse = false,
		weapon = {
			toolName = "Shotgun",
			ammoItem = "shotgun_ammo",
			config = {
				AmmoCapacity = 5,
				FullDamageDistance = 25,
				HitDamage = 20,
				MaxSpread = 1.5,
				MinSpread = 0.8,
				MuzzleFlashSize0 = 1.3,
				MuzzleFlashSize1 = 1.6,
				NumProjectiles = 8,
				RecoilDecay = 0.95,
				RecoilMax = 1.6,
				RecoilMin = 1.5,
				ShotCooldown = 0.8,
				TotalRecoilMax = 2.2,
				ZeroDamageDistance = 250,
			},
		},
		description = "A close-range shotgun backed by a Roblox Tool template.",
	},

	weapon_auto_rifle = {
		name = "weapon_auto_rifle",
		label = "Auto Rifle",
		weight = 3200,
		type = "weapon",
		image = "rbxassetid://101959889781255",
		unique = true,
		useable = true,
		shouldClose = true,
		removeOnUse = false,
		weapon = {
			toolName = "Auto Rifle",
			toolNames = { "AR" },
			ammoItem = "rifle_ammo",
			config = {
				AmmoCapacity = 30,
				FireMode = "Automatic",
				GravityFactor = 0.5,
				HitDamage = 20,
				MaxSpread = 0.6,
				MuzzleFlashSize0 = 1.1,
				MuzzleFlashSize1 = 1.4,
				RecoilDecay = 0.81,
				RecoilMax = 0.9,
				RecoilMin = 0.7,
				ShotCooldown = 0.8,
				TotalRecoilMax = 1.1,
			},
		},
		description = "An automatic rifle backed by a Roblox Tool template.",
	},

	weapon_submachine_gun = {
		name = "weapon_submachine_gun",
		label = "Submachine Gun",
		weight = 2600,
		type = "weapon",
		image = "rbxassetid://115054211769765",
		unique = true,
		useable = true,
		shouldClose = true,
		removeOnUse = false,
		weapon = {
			toolName = "Submachine Gun",
			toolNames = { "SMG" },
			ammoItem = "smg_ammo",
			config = {
				AmmoCapacity = 30,
				FireMode = "Automatic",
				GravityFactor = 0.5,
				HitDamage = 9,
				MaxSpread = 1,
				MuzzleFlashSize0 = 0.75,
				MuzzleFlashSize1 = 0.95,
				RecoilDecay = 0.87,
				RecoilMax = 0.55,
				RecoilMin = 0.5,
				ShotCooldown = 0.075,
				TotalRecoilMax = 1.5,
			},
		},
		description = "A compact automatic weapon backed by a Roblox Tool template.",
	},

	weapon_sniper_rifle = {
		name = "weapon_sniper_rifle",
		label = "Sniper Rifle",
		weight = 4500,
		type = "weapon",
		image = "rbxassetid://99950141783775",
		unique = true,
		useable = true,
		shouldClose = true,
		removeOnUse = false,
		weapon = {
			toolName = "Sniper Rifle",
			toolNames = { "Sniper" },
			ammoItem = "sniper_ammo",
			config = {
				AmmoCapacity = 5,
				GravityFactor = 0.5,
				HitDamage = 100,
				MuzzleFlashSize0 = 1.25,
				MuzzleFlashSize1 = 1.8,
				RecoilDecay = 0.75,
				RecoilMax = 1.5,
				RecoilMin = 1,
				ShotCooldown = 2.5,
				TotalRecoilMax = 1.5,
			},
		},
		description = "A precision rifle backed by a Roblox Tool template.",
	},

	weapon_crossbow = {
		name = "weapon_crossbow",
		label = "Crossbow",
		weight = 3000,
		type = "weapon",
		image = "",
		unique = true,
		useable = true,
		shouldClose = true,
		removeOnUse = false,
		weapon = {
			toolName = "Crossbow",
			ammoItem = "bolt_ammo",
			config = {
				AmmoCapacity = 30,
				BulletSpeed = 425,
				ChargeRate = 2,
				DischargeRate = 0.25,
				HitDamage = 100,
				RecoilDecay = 0.975,
				RecoilDelayTime = 0.01,
				RecoilMax = 1.5,
				RecoilMin = 1.25,
				ShotCooldown = 0.2,
				TotalRecoilMax = 2.5,
			},
		},
		description = "A projectile crossbow backed by a Roblox Tool template.",
	},

	weapon_grenade_launcher = {
		name = "weapon_grenade_launcher",
		label = "Grenade Launcher",
		weight = 6500,
		type = "weapon",
		image = "rbxassetid://77692204023108",
		unique = true,
		useable = true,
		shouldClose = true,
		removeOnUse = false,
		weapon = {
			toolName = "Grenade Launcher",
			ammoItem = "grenade_ammo",
			config = {
				AmmoCapacity = 6,
				BlastDamage = 75,
				BlastPressure = 20000,
				BlastRadius = 16,
				BulletSpeed = 150,
				GravityFactor = 1,
				HitDamage = 100,
				NumProjectiles = 1,
				RecoilDecay = 0.98,
				RecoilMax = 1.6,
				RecoilMin = 1.2,
				ReloadTime = 2.4,
				ShotCooldown = 1.35,
				TotalRecoilMax = 1.9,
			},
		},
		description = "An explosive launcher backed by a Roblox Tool template.",
	},

	weapon_rocket_launcher = {
		name = "weapon_rocket_launcher",
		label = "Rocket Launcher",
		weight = 8000,
		type = "weapon",
		image = "rbxassetid://86908335274824",
		unique = true,
		useable = true,
		shouldClose = true,
		removeOnUse = false,
		weapon = {
			toolName = "Rocket Launcher",
			ammoItem = "rocket_ammo",
		},
		description = "A heavy rocket launcher backed by a Roblox Tool template.",
	},

	weapon_railgun = {
		name = "weapon_railgun",
		label = "Railgun",
		weight = 7000,
		type = "weapon",
		image = "rbxassetid://109985949045891",
		unique = true,
		useable = true,
		shouldClose = true,
		removeOnUse = false,
		weapon = {
			toolName = "Railgun",
			ammoItem = "railgun_ammo",
			config = {
				AmmoCapacity = 5,
				BlastDamage = 75,
				BlastPressure = 20000,
				BlastRadius = 5,
				BulletSpeed = 20000,
				ChargeRate = 1.2,
				HitDamage = 75,
				MaxDistance = 1000,
				NumProjectiles = 1,
				RecoilDecay = 0.95,
				RecoilMax = 7,
				RecoilMin = 6.5,
				TotalRecoilMax = 7.1,
			},
		},
		description = "An energy weapon backed by a Roblox Tool template.",
	},
}
